name: Release & Tracker Issue

on:
  push:
    branches:
      - main
  issue_comment:
    types: [edited]
  issues:
    types: [edited]

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Release
        uses: onezerocompany/coding/actions/release-tracker@feat/release-tracker
