name: Release & Tracker Issue

on:
  push:
    branches:
      - main
  issue_comment:
    types: [edited]
  issues:
    types: [edited]

concurrency:
  # group by sha of pushed commit or issue number
  group: release-tracker-${{ github.event.issue.number || github.sha }}
  cancel-in-progress: true

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      # make sure the git information is available for the release-tracker action
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create test file
        run: |
          echo "test" > TEST.md

      - name: Create build files
        run: |
          mkdir -p build
          echo "build" > build/build.txt
          echo "build2" > build/build2.txt
          echo "build3" > build/build3.txt

      # run the release-tracker action, it auto detects what to do
      - name: Release Tracker
        uses: onezerocompany/coding/actions/release-tracker@feat/release-tracker-files
        with:
          files: |
            build/**/*
            TEST.md
            doesnotexist.txt
